h

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,16 +28,16 @@ jobs:
       - name: Run tests
         run: npm test
       - name: Run tests and check coverage
-      run: |
-        coverage=$(npx jest --showConfig \
-          | grep coverageThreshold \
-          | awk '{print $3}' \
-          | tr -d ',' \
-          | sed 's/"//g')
-        threshold=50
-        if (( $(echo "$coverage < $threshold" | bc -l) )); then
-          echo "Test coverage is less than $threshold%. Aborting merge."
-          exit 1
-        fi
+        run: |
+          coverage=$(npx jest --showConfig \
+            | grep coverageThreshold \
+            | awk '{print $3}' \
+            | tr -d ',' \
+            | sed 's/"//g')
+          threshold=50
+          if (( $(echo "$coverage < $threshold" | bc -l) )); then
+            echo "Test coverage is less than $threshold%. Aborting merge."
+            exit 1
+          fi
 
 
